import { defineField, defineType } from 'sanity'
import { ThLargeIcon } from '@sanity/icons'

export const projectsMasonry = defineType({
  name: 'projectsMasonry',
  title: 'Projects Masonry Grid',
  type: 'object',
  icon: ThLargeIcon,
  fields: [
    defineField({
      name: 'eyebrow',
      title: 'Eyebrow',
      type: 'string',
      initialValue: 'Архив',
    }),
    defineField({
      name: 'heading',
      title: 'Heading',
      type: 'string',
      initialValue: 'Изберете сектор и разгледайте проектите.',
    }),
    defineField({
      name: 'items',
      title: 'Project cards',
      type: 'array',
      of: [
        {
          type: 'object',
          name: 'projectCard',
          title: 'Project card',
          fields: [
            defineField({ name: 'title', type: 'string', title: 'Title' }),
            defineField({ name: 'sector', type: 'string', title: 'Sector key', description: 'e.g. healthcare, hotel, retail, industrial, government' }),
            defineField({ name: 'sectorLabel', type: 'string', title: 'Sector label (Bulgarian)' }),
            defineField({ name: 'year', type: 'string', title: 'Year / period' }),
            defineField({
              name: 'image',
              type: 'image',
              title: 'Image',
              options: { hotspot: true },
            }),
            defineField({ name: 'imageFallback', type: 'string', title: 'Image fallback path', description: '/nikom/proj-*.jpg' }),
            defineField({ name: 'href', type: 'string', title: 'Link href', description: '/bg/proekti/<slug>' }),
            defineField({
              name: 'systems',
              type: 'array',
              title: 'Systems / chips',
              of: [{ type: 'string' }],
            }),
            defineField({
              name: 'kpis',
              title: 'KPI items',
              type: 'array',
              of: [
                {
                  type: 'object',
                  name: 'cardKpi',
                  title: 'KPI',
                  fields: [
                    defineField({ name: 'label', type: 'string', title: 'Label' }),
                    defineField({ name: 'value', type: 'string', title: 'Value' }),
                  ],
                  preview: {
                    select: { label: 'label', value: 'value' },
                    prepare({ label, value }) {
                      return { title: value, subtitle: label }
                    },
                  },
                },
              ],
            }),
            defineField({ name: 'classified', type: 'boolean', title: 'Classified', initialValue: false }),
            defineField({ name: 'size', type: 'string', title: 'Card size hint', options: { list: ['normal', 'featured'] }, initialValue: 'normal' }),
          ],
          preview: {
            select: { title: 'title', sectorLabel: 'sectorLabel', image: 'image' },
            prepare({ title, sectorLabel, image }) {
              return { title: title ?? 'Card', subtitle: sectorLabel, media: image }
            },
          },
        },
      ],
      initialValue: [
        {
          title: '„Аджибадем Сити Клиник Болница Токуда" ЕАД',
          sector: 'healthcare',
          sectorLabel: 'Здравеопазване',
          year: '2010 — наст.',
          imageFallback: '/nikom/proj-tokuda.jpg',
          href: '/bg/proekti/project-35',
          systems: ['Пожароизвестяване Esser by Honeywell', 'Спринклерна пожарогасителна', 'Пожарни кранове'],
          kpis: [{ label: 'Детектори', value: '2 000' }, { label: 'Спринклери', value: '4 800' }],
          classified: false,
          size: 'featured',
        },
        {
          title: 'Верига магазини ХИПОЛЕНД',
          sector: 'retail',
          sectorLabel: 'Ритейл',
          year: '2019 — наст.',
          imageFallback: '/nikom/proj-hipoland.jpg',
          href: '/bg/proekti/project-42',
          systems: ['Пожароизвестяване', 'Видеонаблюдение', 'Сигнално-охранителни системи', 'Озвучаване'],
          kpis: [{ label: 'Обекта', value: '28+' }, { label: 'SLA', value: '99.5%' }],
          classified: false,
          size: 'normal',
        },
        {
          title: '„НСБАЛХЗ" ЕАД — Болница по Хематология, гр. София',
          sector: 'healthcare',
          sectorLabel: 'Здравеопазване',
          year: '2021',
          imageFallback: '/nikom/proj-onkobolnitsa.jpg',
          href: '/bg/proekti/nsbalkhz-ead-bolnitca-po-khematologiia-gr.sofiia',
          systems: ['Пожароизвестяване', 'Сигнално-охранителна', 'Силнотокови инсталации', 'СКС'],
          kpis: [{ label: 'Чисти зони', value: '12' }, { label: 'Точки за SKS', value: '850+' }],
          classified: false,
          size: 'normal',
        },
        {
          title: 'Посолство и резиденция на Република ПОЛША, София',
          sector: 'government',
          sectorLabel: 'Държавни',
          year: '2020',
          imageFallback: '/nikom/proj-poland.jpg',
          href: '/bg/proekti/posolstvo-i-rezidentciia-na-republika-polsha-sofiia',
          systems: ['Видеонаблюдение', 'Контрол на достъп', 'Видеодомофонна система'],
          kpis: [{ label: 'Ниво', value: 'Дипл.' }, { label: 'Резервиране', value: 'N+1' }],
          classified: true,
          size: 'normal',
        },
        {
          title: 'Складова база GOPET TRANS, гр. София',
          sector: 'industrial',
          sectorLabel: 'Складове',
          year: '2018',
          imageFallback: '/nikom/proj-gopet.jpg',
          href: '/bg/proekti/skladova-baza-gopet-trans-gr.sofiia-4000-kv.m',
          systems: ['Пожароизвестяване', 'Видеонаблюдение', 'Контрол на достъп', 'Паркинг', 'Охранителна'],
          kpis: [{ label: 'Площ', value: '4 000 m²' }, { label: 'Камери', value: '48' }],
          classified: false,
          size: 'normal',
        },
        {
          title: 'Хотелски комплекс ИЗВОРИТЕ, гр. Разлог',
          sector: 'hotel',
          sectorLabel: 'Хотели',
          year: '2017',
          imageFallback: '/nikom/proj-izvorite.jpg',
          href: '/bg/proekti/khotelski-kompleks-izvorite-gr.razlog',
          systems: ['Пожароизвестяване', 'Оповестителна и SOS системи'],
          kpis: [{ label: 'Стаи', value: '85' }, { label: 'EN 54-16', value: 'ДА' }],
          classified: false,
          size: 'normal',
        },
        {
          title: 'Хотел АНЕЛ 5★, гр. София',
          sector: 'hotel',
          sectorLabel: 'Хотели',
          year: '2015',
          imageFallback: '/nikom/proj-anel.jpg',
          href: '/bg/proekti/khotel-anel-5-gr-sofiia',
          systems: ['Пожароизвестяване'],
          kpis: [{ label: 'Етажи', value: '11' }, { label: 'Стаи', value: '84' }],
          classified: false,
          size: 'normal',
        },
        {
          title: 'Бутиков хотел Кристал Палас 4★, гр. София',
          sector: 'hotel',
          sectorLabel: 'Хотели',
          year: '2014',
          imageFallback: '/nikom/proj-crystal.jpg',
          href: '/bg/proekti/butikov-khotel-kristal-palas-4-gr.sofiia',
          systems: ['Пожароизвестяване', 'Видеонаблюдение'],
          kpis: [{ label: 'Стаи', value: '62' }],
          classified: false,
          size: 'normal',
        },
        {
          title: 'Хотел Arena di Serdika 5★, гр. София',
          sector: 'hotel',
          sectorLabel: 'Хотели',
          year: '2016',
          imageFallback: '/nikom/proj-arena.jpg',
          href: '/bg/proekti/khotel-arena-di-serdika-5-gr.sofiia',
          systems: ['Пожароизвестяване', 'Видеонаблюдение', 'Контрол на достъп'],
          kpis: [{ label: 'Стаи', value: '140' }, { label: 'Зали', value: '5' }],
          classified: false,
          size: 'normal',
        },
        {
          title: 'Арт хотелски комплекс АНЕЛ, гр. Созопол',
          sector: 'hotel',
          sectorLabel: 'Хотели',
          year: '2019',
          imageFallback: '/nikom/proj-sozopol.jpg',
          href: '/bg/proekti/art-khotelski-kompleks-anel-gr-sozopol',
          systems: ['Пожароизвестяване', 'СКС'],
          kpis: [{ label: 'Сезон', value: '12/12 мес.' }],
          classified: false,
          size: 'normal',
        },
        {
          title: 'Обект на Министерство на отбраната',
          sector: 'government',
          sectorLabel: 'Държавни',
          year: '2022',
          imageFallback: '/nikom/proj-mod.jpg',
          href: '/bg/proekti/obekt-ministerstvo-na-otbranata-gazovo-pozhargasene',
          systems: ['Газова автоматична пожарогасителна инсталация'],
          kpis: [{ label: 'Тип агент', value: 'FM-200' }, { label: 'Зони', value: '3' }],
          classified: true,
          size: 'normal',
        },
      ],
    }),
  ],
  preview: {
    select: { heading: 'heading' },
    prepare({ heading }) {
      return {
        title: heading ?? 'Projects Masonry',
        subtitle: 'projectsMasonry',
      }
    },
  },
})
